module.exports = {
  __swagger__: {
    name: '测试用例接口',
    description: '测试用例接口'
  },
  '/one': {
    name: 'demo接口1',
    desc: 'demo接口1',
    method: 'get',
    controller: 'test.one',
    param: { },
    'token': false,
    'needSign': false,
    'err_code': {},
    'test': {},
    'front': true
  },
  '/testErrCode': {
    name: '测试errCode',
    desc: '测试errCode',
    method: 'get',
    controller: 'test.testErrCode',
    param: { },
    'token': false,
    'needSign': false,
    'err_code': {},
    'test': {},
    'front': true
  },
  '/testErrCodeArr': {
    name: '测试errCode',
    desc: '测试errCode',
    method: 'get',
    controller: 'test.testErrCodeArr',
    param: { },
    'token': false,
    'needSign': false,
    'err_code': {},
    'test': {},
    'front': true
  },
  '/testErrCodeObj': {
    name: '测试errCode',
    desc: '测试errCode',
    method: 'get',
    controller: 'test.testErrCodeObj',
    param: { },
    'token': false,
    'needSign': false,
    'err_code': {},
    'test': {},
    'front': true
  },
  '/testErrCodeErr': {
    name: '测试errCode',
    desc: '测试errCode',
    method: 'get',
    controller: 'test.testErrCodeErr',
    param: { },
    'token': false,
    'needSign': false,
    'err_code': {},
    'test': {},
    'front': true
  },
  '/testErr': {
    name: '测试异常',
    desc: '测试异常',
    method: 'get',
    controller: 'test.testErr',
    param: { },
    'token': false,
    'needSign': false,
    'err_code': {},
    'test': {},
    'front': true
  },
  '/testNoName': {
    method: 'get',
    controller: 'test.testErrCodeObj',
    param: { },
    'token': false,
    'needSign': false,
    'err_code': {},
    'test': {},
    'front': true
  },
  '/testErr_Code_Obj': {
    name: '测试errCode',
    desc: '测试errCode',
    method: 'get',
    controller: 'test.testErrCodeObj',
    param: { },
    'token': false,
    'needSign': false,
    'err_code': {},
    'test': {},
    'front': true
  },
  '/noController': {
    name: '',
    desc: '',
    method: 'get',
    controller: 'test.noController',
    param: { },
    'token': false,
    'needSign': false,
    'err_code': {},
    'test': {},
    'front': true
  },
  '/noFile': {
    name: '',
    desc: '',
    method: 'get',
    controller: 'asdf.noFile',
    param: { },
    'token': false,
    'needSign': false,
    'err_code': {},
    'test': {},
    'front': true
  },
  '/mock/image': {
    name: '',
    desc: '',
    method: 'get',
    feqLimit: 1000,
    controller: 'test.two',
    param: { },
    'token': false,
    'needSign': false,
    'err_code': {},
    'test': {},
    'front': true
  },
  '/testReturn': {
    name: '',
    desc: '',
    method: 'get',
    feqLimit: 1000,
    controller: 'test.testReturn',
    param: { },
    'token': false,
    'needSign': false,
    'err_code': {},
    'test': {},
    'front': true
  }
}
